name: base_approach
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  mobx: ^0.3.9+3
  flutter_mobx: ^0.3.3+3
  redux: ^3.0.0
  flutter_redux: ^0.5.4
  redux_logging: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.10+1

flutter:
  uses-material-design: true